# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-05 14:56
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time', models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430 \u043d\u0430\u0441\u0442\u0443\u043f\u043b\u0435\u043d\u0438\u044f')),
                ('mens', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='\u0423\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u0438')),
            ],
            options={
                'verbose_name_plural': '\u041d\u0430\u043f\u043e\u043c\u0438\u043d\u0430\u043b\u043a\u0438',
            },
        ),
    ]
