# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice_Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/', verbose_name='\u0423\u043a\u0430\u0436\u0438\u0442\u0435 \u0444\u0430\u0439\u043b')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Notice')),
            ],
        ),
        migrations.CreateModel(
            name='Notice_Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dolgota', models.CharField(max_length=500, verbose_name='\u0414\u043e\u043b\u0433\u043e\u0442\u0430')),
                ('wirota', models.CharField(max_length=500, verbose_name='\u0428\u0438\u0440\u043e\u0442\u0430')),
                ('notice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Notice')),
            ],
        ),
    ]
