# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_notice_files_notice_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
