# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-07 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160907_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='\u0410\u0432\u0430\u0442\u0430\u0440'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='phone',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d'),
        ),
    ]
