# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-07 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160907_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.User_Profile'),
        ),
    ]
