# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 07:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_notice_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='mens',
            field=models.ManyToManyField(related_name='mens', to=settings.AUTH_USER_MODEL, verbose_name='\u0423\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
