# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-11 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice_files',
            name='notice',
        ),
        migrations.AddField(
            model_name='notice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='\u041f\u0440\u0438\u043a\u0440\u0435\u043f\u0438\u0442\u044c \u0444\u0430\u0439\u043b'),
        ),
        migrations.DeleteModel(
            name='Notice_Files',
        ),
    ]
